services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200" # Replace with your Elasticsearch URL
      # Optional Settings
      # KIBANA_PWD: "your_kibana_password" 
      # ELASTICSEARCH_USERNAME: "elastic"
      # ELASTICSEARCH_PASSWORD: "your_password"
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    restart: always
    container_name: elasticsearch-container
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false 
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # Reduce heap size to 512MB
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "elasticvolume:/usr/share/elasticsearch/data:cached"
volumes:
  elasticvolume:
    driver: local