CREATE TYPE "cp_role_enum" AS ENUM (
  'Supervisior',
  'Worker',
  'Central_Consultant',
  'Central_Consultant_Manager',
  'Support_Assitant',
  'Area_Manager',
  'Executive_Manager',
  'CIA_Change_Management',
  'CIA_Management',
  'Administrator',
  'Super_Admin'
); 

CREATE TYPE "case_status_enum" AS ENUM (
  'Pending_Victim_Contact',
  'Pending_Decision',
  'Pending_Closure',
  'Closed'
);

CREATE TYPE "huddle_status_enum" AS ENUM (
  'Needed',
  'Occured',
  'Not_needed',
  'Cancelled',
  'Reschduled'
);

CREATE TYPE "escalation_view" AS ENUM (
  'Supervisor',
  'Case_worker',
  'Central_Consultant'
);

CREATE TYPE "scope" AS ENUM (
  'Tenant',
  'Area',
  'Team',
  'Self',
  'No'
);

CREATE TYPE "tenant_status" AS ENUM (
  'Active',
  'Inactive'
);

CREATE TYPE "mapping_status" AS ENUM (
  'Completed',
  'In Progress',
  'Yet To Start'
);

CREATE TYPE "named_query_feature_list" AS ENUM (
  'Huddle Board',
  'Huddle Reason',
  'Case Loads',
  'Consult Logs',
  'Escalations',
  'Speciality Team Assignment',
  'Badges'
);

CREATE TABLE "global_cp_role" (
  "cp_role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cp_role_name" cp_role_enum UNIQUE NOT NULL,
  "cp_role_display_name" varcFhar(50),
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);

CREATE TABLE "global_huddle_status" (
  "huddle_status_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "huddle_status_name" huddle_status_enum UNIQUE NOT NULL,
  "huddle_status_display_name" varchar(50),
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "global_huddle_status" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "global_huddle_status" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");


CREATE TABLE "global_domain_realm" (
  "domain_realm_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "domain_name" varchar(30) UNIQUE NOT NULL,
  "realm" varchar(30) NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "global_domain_realm" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "global_domain_realm" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");

CREATE TABLE "global_tenant" (
  "tenant_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tenant_name" varchar(50) NOT NULL,
  "tenant_details" varchar(200) NOT NULL,
  "tenant_status" tenant_status NOT NULL,
  "mapping_status" mapping_status NOT NULL,
  "decommision" boolean NOT NULL,
  "schema_id" int NOT NULL,
  "deleted" boolean NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL,
  "deleted_by" int,
  "deleted_date" date
);
ALTER TABLE "global_tenant" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "global_tenant" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "global_tenant" ADD FOREIGN KEY ("schema_id") REFERENCES "global_schema" ("schema_id");
ALTER TABLE "global_tenant" ADD FOREIGN KEY ("deleted_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");

CREATE TABLE "global_schema" (
  "schema_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "schema_name" varchar(50),
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "global_schema" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "global_schema" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");

CREATE TABLE "area" (
  "area_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "area_name" varchar NOT NULL,
  "area_display_name" varchar(100),
  "seq_id" int NOT NULL,
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "area" ADD FOREIGN KEY ("tenant_id") REFERENCES "global_tenant" ("tenant_id");
ALTER TABLE "area" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "area" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
CREATE UNIQUE INDEX "unique_area_name_for_tenant" ON "area" ("area_display_name", "tenant_id");
CREATE UNIQUE INDEX "unique_area_for_tenant" ON "area" ("area_id", "tenant_id");

CREATE TABLE "team" (
  "team_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "area_id" int NOT NULL,
  "team_name" varchar(100) NOT NULL,
  "seq_id" int NOT NULL,
  "team_display_name" varchar,
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "team" ADD FOREIGN KEY ("area_id") REFERENCES "area" ("area_id");
ALTER TABLE "team" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "team" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "team" ADD FOREIGN KEY ("area_id", "tenant_id") REFERENCES "area" ("area_id", "tenant_id");
CREATE UNIQUE INDEX "unique_team_for_tenant" ON "team" ("team_id", "tenant_id");
CREATE UNIQUE INDEX "unique_team_name_for_area_and_tenant" ON "team" ("team_display_name", "area_id", "tenant_id");

CREATE TABLE "global_cp_user_master" (
  "cp_user_master_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_name" varchar(50) NOT NULL,
  "user_email" varchar UNIQUE NOT NULL,
  "user_status" boolean NOT NULL,
  "last_login" date,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "global_cp_user_master" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "global_cp_user_master" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");

CREATE TABLE "workload_label" (
  "workload_label_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workload_label" varchar(50) NOT NULL,
  "workload_display_label" varchar,
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "workload_label" ADD FOREIGN KEY ("tenant_id") REFERENCES "global_tenant" ("tenant_id");
ALTER TABLE "workload_label" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "workload_label" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
CREATE UNIQUE INDEX "unique_workload_display_name_for_tenant" ON "workload_label" ("workload_display_label", "tenant_id");
CREATE UNIQUE INDEX "unique_workload_label_for_tenant" ON "workload_label" ("workload_label", "tenant_id");

CREATE TABLE "cp_user" (
  "cp_user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "team_id" int NOT NULL,
  "role_id" int NOT NULL,
  "cp_user_status" boolean NOT NULL,
  "sor_worker_id" int UNIQUE NOT NULL,
  "global_cp_user_master_id" int NOT NULL,
  "workload_label_id" int NOT NULL,
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "cp_user" ADD FOREIGN KEY ("role_id") REFERENCES "global_role_master" ("role_master_id");
ALTER TABLE "cp_user" ADD FOREIGN KEY ("tenant_id") REFERENCES "global_tenant" ("tenant_id");
ALTER TABLE "cp_user" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "cp_user" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "cp_user" ADD FOREIGN KEY ("team_id", "tenant_id") REFERENCES "team" ("team_id", "tenant_id");
ALTER TABLE "cp_user" ADD FOREIGN KEY ("global_cp_user_master_id") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "cp_user" ADD FOREIGN KEY ("workload_label_id", "tenant_id") REFERENCES "workload_label" ("workload_label_id", "tenant_id");
ALTER TABLE "cp_user" ADD FOREIGN KEY ("team_id") REFERENCES "team" ("team_id");
CREATE UNIQUE INDEX "unique_tenant_cp_user" ON "cp_user" ("tenant_id", "cp_user_id");
CREATE UNIQUE INDEX "unique_tenant_sor_user" ON "cp_user" ("tenant_id", "sor_worker_id");

CREATE TABLE "global_role_master" (
  "role_master_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_name" cp_role_enum UNIQUE NOT NULL,
  "role_name_display" varchar(50) UNIQUE NOT NULL,
  "description" varchar(100) NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "global_role_master" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "global_role_master" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");

CREATE TABLE "global_permission_master" (
  "permission_master_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "module" varchar(20) NOT NULL,
  "permission_name" varchar(50) NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "global_permission_master" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "global_permission_master" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");

CREATE TABLE "role_permission" (
  "role_permission_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_master_id" int NOT NULL,
  "permission_master_id" int NOT NULL,
  "scope" scope NOT NULL,
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "role_permission" ADD FOREIGN KEY ("role_master_id") REFERENCES "global_role_master" ("role_master_id");
ALTER TABLE "role_permission" ADD FOREIGN KEY ("permission_master_id") REFERENCES "global_permission_master" ("permission_master_id");
ALTER TABLE "role_permission" ADD FOREIGN KEY ("tenant_id") REFERENCES "global_tenant" ("tenant_id");
ALTER TABLE "role_permission" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "role_permission" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
CREATE UNIQUE INDEX "unique_role_permission_for_tenant" ON "role_permission" ("role_master_id", "permission_master_id", "tenant_id");

CREATE TABLE "case" (
  "case_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sor_case_id" varchar(30) NOT NULL,
  "case_name" varchar(100) NOT NULL,
  "date_opened" date NOT NULL,
  "sor_worker_id" int NOT NULL,
  "worker_id" int NOT NULL,
  "case_status_id" int NOT NULL,
  "sor_case_status" varchar(20) NOT NULL,
  "sor_local_consult_count" int NOT NULL,
  "sor_central_consult_count" int NOT NULL,
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "case" ADD FOREIGN KEY ("sor_worker_id", "tenant_id") REFERENCES "cp_user" ("sor_worker_id", "tenant_id");
ALTER TABLE "case" ADD FOREIGN KEY ("sor_worker_id") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "case" ADD FOREIGN KEY ("case_status_id") REFERENCES "case_status" ("case_status_id");
ALTER TABLE "case" ADD FOREIGN KEY ("tenant_id") REFERENCES "global_tenant" ("tenant_id");
ALTER TABLE "case" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "case" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "case" ADD FOREIGN KEY ("worker_id") REFERENCES "global_cp_user_master" ("cp_user_master_id");
CREATE UNIQUE INDEX "unique_tenant_case" ON "case" ("tenant_id", "case_id");

CREATE TABLE "finding" (
  "finding_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "case_id" int NOT NULL,
  "finding_description" varchar(100) NOT NULL,
  "victim_id" int NOT NULL,
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "finding" ADD FOREIGN KEY ("case_id") REFERENCES "case" ("case_id");
ALTER TABLE "finding" ADD FOREIGN KEY ("tenant_id") REFERENCES "global_tenant" ("tenant_id");
ALTER TABLE "finding" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "finding" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "finding" ADD FOREIGN KEY ("case_id", "tenant_id") REFERENCES "case" ("case_id", "tenant_id");

CREATE TABLE "allegation" (
  "allegation_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "case_id" int NOT NULL,
  "victim_id" int NOT NULL,
  "allegation_description" varchar(100) NOT NULL,
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "allegation" ADD FOREIGN KEY ("case_id") REFERENCES "case" ("case_id");
ALTER TABLE "allegation" ADD FOREIGN KEY ("tenant_id") REFERENCES "global_tenant" ("tenant_id");
ALTER TABLE "allegation" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "allegation" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "allegation" ADD FOREIGN KEY ("case_id", "tenant_id") REFERENCES "case" ("case_id", "tenant_id");

CREATE TABLE "case_status" (
  "case_status_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "case_status" case_status_enum NOT NULL,
  "case_status_label" varchar(70) NOT NULL,
  "parent_case_status_id" int NOT NULL,
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "case_status" ADD FOREIGN KEY ("tenant_id") REFERENCES "global_tenant" ("tenant_id");
ALTER TABLE "case_status" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "case_status" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
CREATE UNIQUE INDEX "unique_case_status_for_tenant" ON "case_status" ("tenant_id", "case_status_label");

CREATE TABLE "huddle_reason" (
  "huddle_reason_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reason" varchar(100) NOT NULL,
  "named_query_id" int NOT NULL,
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "huddle_reason" ADD FOREIGN KEY ("named_query_id") REFERENCES "named_query" ("named_query_id");
ALTER TABLE "huddle_reason" ADD FOREIGN KEY ("tenant_id") REFERENCES "global_tenant" ("tenant_id");
ALTER TABLE "huddle_reason" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "huddle_reason" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");

CREATE TABLE "huddle_to_huddle_reason" (
  "huddle_to_huddle_reason_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "huddle_id" int NOT NULL,
  "huddle_reason_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "huddle_to_huddle_reason" ADD FOREIGN KEY ("huddle_id") REFERENCES "huddle" ("huddle_id");
ALTER TABLE "huddle_to_huddle_reason" ADD FOREIGN KEY ("huddle_reason_id") REFERENCES "huddle_reason" ("huddle_reason_id");
ALTER TABLE "huddle_to_huddle_reason" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "huddle_to_huddle_reason" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");

CREATE TABLE "huddle" (
  "huddle_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "case_id" int NOT NULL,
  "huddle_status_id" int NOT NULL,
  "last_huddle_data" date NOT NULL,
  "next_huddle_data" date NOT NULL,
  "huddle_frequency" int NOT NULL,
  "huddle_notes" varchar(5000) NOT NULL,
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "huddle" ADD FOREIGN KEY ("huddle_status_id") REFERENCES "global_huddle_status" ("huddle_status_id");
ALTER TABLE "huddle" ADD FOREIGN KEY ("case_id") REFERENCES "case" ("case_id");
ALTER TABLE "huddle" ADD FOREIGN KEY ("tenant_id") REFERENCES "global_tenant" ("tenant_id");
ALTER TABLE "huddle" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "huddle" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");

CREATE TABLE "victim" (
  "victim_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "case_id" int NOT NULL,
  "sor_victim_id" varchar(20) NOT NULL,
  "name" varchar NOT NULL,
  "date_of_birth" date,
  "address" varchar(200),
  "contactnumber" int,
  "victim_seen" boolean NOT NULL,
  "initial_seen" date,
  "last_seen" date,
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "victim" ADD FOREIGN KEY ("case_id") REFERENCES "case" ("case_id");
ALTER TABLE "victim" ADD FOREIGN KEY ("tenant_id") REFERENCES "global_tenant" ("tenant_id");
ALTER TABLE "victim" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "victim" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "victim" ADD FOREIGN KEY ("case_id", "tenant_id") REFERENCES "case" ("case_id", "tenant_id");

CREATE TABLE "scenario" (
  "scenario_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "scenario_name" varchar(100) UNIQUE NOT NULL,
  "scenario_display" varchar(200),
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "scenario" ADD FOREIGN KEY ("tenant_id") REFERENCES "global_tenant" ("tenant_id");
ALTER TABLE "scenario" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "scenario" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
CREATE UNIQUE INDEX "unique_tenant_scenario" ON "scenario" ("tenant_id", "scenario_id");

CREATE TABLE "case_scenario" (
  "case_scenario_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "case_id" int NOT NULL,
  "tenant_id" int NOT NULL,
  "scenario_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "case_scenario" ADD FOREIGN KEY ("case_id") REFERENCES "case" ("case_id");
ALTER TABLE "case_scenario" ADD FOREIGN KEY ("scenario_id") REFERENCES "scenario" ("scenario_id");
ALTER TABLE "case_scenario" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "case_scenario" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "case_scenario" ADD FOREIGN KEY ("scenario_id", "tenant_id") REFERENCES "scenario" ("scenario_id", "tenant_id");
ALTER TABLE "case_scenario" ADD FOREIGN KEY ("case_id", "tenant_id") REFERENCES "case" ("case_id", "tenant_id");
CREATE UNIQUE INDEX "unique_case_scenario" ON "case_scenario" ("scenario_id", "case_id");

CREATE TABLE "task_type" (
  "task_type_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_type" varchar(100) NOT NULL,
  "task_type_enabled" boolean NOT NULL,
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "task_type" ADD FOREIGN KEY ("tenant_id") REFERENCES "global_tenant" ("tenant_id");
ALTER TABLE "task_type" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "task_type" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");

CREATE TABLE "support_task" (
  "support_task_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_type_id" int NOT NULL,
  "task_name" varchar NOT NULL,
  "task_enabled" boolean NOT NULL,
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "support_task" ADD FOREIGN KEY ("task_type_id") REFERENCES "task_type" ("task_type_id");
ALTER TABLE "support_task" ADD FOREIGN KEY ("tenant_id") REFERENCES "global_tenant" ("tenant_id");
ALTER TABLE "support_task" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "support_task" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");

CREATE TABLE "case_support_task" (
  "case_support_task_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "support_task_id" int NOT NULL,
  "case_id" int NOT NULL,
  "status" varchar(50),
  "requested_by" int,
  "request_date" date,
  "started_by" int,
  "start_date" date,
  "closed_by" int,
  "close_date" date,
  "case_instructions" varchar,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "case_support_task" ADD FOREIGN KEY ("support_task_id") REFERENCES "support_task" ("support_task_id");
ALTER TABLE "case_support_task" ADD FOREIGN KEY ("case_id") REFERENCES "case" ("case_id");
ALTER TABLE "case_support_task" ADD FOREIGN KEY ("requested_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "case_support_task" ADD FOREIGN KEY ("started_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "case_support_task" ADD FOREIGN KEY ("closed_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "case_support_task" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "case_support_task" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
CREATE UNIQUE INDEX "unique_case_support_task" ON "case_support_task" ("support_task_id", "case_id");

CREATE TABLE "named_query" (
  "named_query_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "query_name" varchar(200) NOT NULL,
  "query_preference" varchar(20) NOT NULL,
  "filter_query" varchar(2000),
  "filter_json" varchar(2000),
  "entity" varchar NOT NULL,
  "last_modified" date NOT NULL,
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "named_query" ADD FOREIGN KEY ("tenant_id") REFERENCES "global_tenant" ("tenant_id");
ALTER TABLE "named_query" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "named_query" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");

CREATE TABLE "named_query_feature" (
  "name_query_feature_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "named_query_id" int NOT NULL,
  "feature" named_query_feature_list NOT NULL
);
ALTER TABLE "named_query_feature" ADD FOREIGN KEY ("named_query_id") REFERENCES "named_query" ("named_query_id");

CREATE TABLE "consult_config" (
  "consult_config_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "outcome" varchar(200) NOT NULL,
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "consult_config" ADD FOREIGN KEY ("tenant_id") REFERENCES "global_tenant" ("tenant_id");
ALTER TABLE "consult_config" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "consult_config" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
CREATE UNIQUE INDEX "unique_consult_config_for_tenant" ON "consult_config" ("consult_config_id", "tenant_id");
CREATE UNIQUE INDEX "unique_consult_outcome_for_tenant" ON "consult_config" ("outcome", "tenant_id");

CREATE TABLE "consult" (
  "consult_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "consult_config_id" int NOT NULL,
  "case_id" int NOT NULL,
  "consult_date" date NOT NULL,
  "notes" varchar(5000),
  "consult_person" int NOT NULL,
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "consult" ADD FOREIGN KEY ("consult_person") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "consult" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "consult" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "consult" ADD FOREIGN KEY ("case_id") REFERENCES "case" ("case_id");
ALTER TABLE "consult" ADD FOREIGN KEY ("consult_config_id", "tenant_id") REFERENCES "consult_config" ("consult_config_id", "tenant_id");

CREATE TABLE "escalation" (
  "escalation_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "escalation_title" varchar(100),
  "escalation_view" escalation_view NOT NULL,
  "named_query_id" int NOT NULL,
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "escalation" ADD FOREIGN KEY ("named_query_id") REFERENCES "named_query" ("named_query_id");
ALTER TABLE "escalation" ADD FOREIGN KEY ("tenant_id") REFERENCES "global_tenant" ("tenant_id");
ALTER TABLE "escalation" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "escalation" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "escalation" ADD FOREIGN KEY ("escalation_id", "tenant_id") REFERENCES "case_escalation" ("escalation_id", "tenant_id");
CREATE UNIQUE INDEX "unique_escalation_for_tenant" ON "escalation" ("escalation_id", "tenant_id");

CREATE TABLE "escalation_role" (
  "escalation_role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role" varchar NOT NULL,
  "escalation_view" escalation_view NOT NULL,
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "escalation_role" ADD FOREIGN KEY ("tenant_id") REFERENCES "global_tenant" ("tenant_id");
ALTER TABLE "escalation_role" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "escalation_role" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");

CREATE TABLE "case_escalation" (
  "case_escalation_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "escalation_id" int NOT NULL,
  "case_id" int NOT NULL,
  "cp_user_id" int NOT NULL,
  "escalation_deadline" date,
  "escalation_notes" varchar(1000) NOT NULL,
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "case_escalation" ADD FOREIGN KEY ("escalation_id") REFERENCES "escalation" ("escalation_id");
ALTER TABLE "case_escalation" ADD FOREIGN KEY ("case_id") REFERENCES "case" ("case_id");
ALTER TABLE "case_escalation" ADD FOREIGN KEY ("cp_user_id") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "case_escalation" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "case_escalation" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");

CREATE TABLE "badge" (
  "badge_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "badge_name" varchar(100) NOT NULL,
  "named_query_id" int NOT NULL,
  "image" bytes NOT NULL,
  "priority" int NOT NULL,
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "badge" ADD FOREIGN KEY ("tenant_id") REFERENCES "global_tenant" ("tenant_id");
ALTER TABLE "badge" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "badge" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
CREATE UNIQUE INDEX "unique_tenant_badge" ON "badge" ("named_query_id", "tenant_id");

CREATE TABLE "case_badge" (
  "case_badge_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "badge_id" int NOT NULL,
  "case_id" int NOT NULL,
  "enabled" bool NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "case_badge" ADD FOREIGN KEY ("badge_id") REFERENCES "badge" ("badge_id");
ALTER TABLE "case_badge" ADD FOREIGN KEY ("case_id") REFERENCES "case" ("case_id");
ALTER TABLE "case_badge" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "case_badge" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
CREATE UNIQUE INDEX "unique_case_badge" ON "case_badge" ("badge_id", "case_id");

CREATE TABLE "days_open" (
  "days_open_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "days" int NOT NULL,
  "operator" varchar(2),
  "label" varchar(20) NOT NULL,
  "color" varchar(20) NOT NULL,
  "tenant_id" int NOT NULL,
  "created_by" int NOT NULL,
  "created_date" date NOT NULL,
  "updated_by" int NOT NULL,
  "updated_date" date NOT NULL
);
ALTER TABLE "days_open" ADD FOREIGN KEY ("tenant_id") REFERENCES "global_tenant" ("tenant_id");
ALTER TABLE "days_open" ADD FOREIGN KEY ("created_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
ALTER TABLE "days_open" ADD FOREIGN KEY ("updated_by") REFERENCES "global_cp_user_master" ("cp_user_master_id");
