services:
  adminportal:
    image: adminportal:latest
    restart: always
    container_name: adminportal-container
    environment:
      - KEYCLOAK_CLIENT_ID_MAINAPPRLM=mainappclt
      - KEYCLOAK_CLIENT_SECRET_MAINAPPRLM=Mgb4X/5RaqAojphemSxN+NLOoSm/+lMLzcHEFmlbrU4
      - KEYCLOAK_ISSUER=http://host.docker.internal:7119/realms/mainapprlm
      - NEXT_PUBLIC_BACEND_SERVER_URL=http://host.docker.internal:7124
      - NEXTAUTH_URL=http://host.docker.internal:7122
      - NEXTAUTH_SECRET=HkdemDq6a0mjQP6BKOkczyHedcF70tSC9esuBUuUvlk=
    ports:
      - "7121:3000"
